[package]
name = "clinvar_annotation_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
csv = "1.3.1"
flate2 = "1.0.35"
serde = { version = "1.0.216", features = ["derive"] }
